[package]
name = "webpack-q-cli"
version = "0.2.0"
edition = "2021"
repository = ""
description = "Ask questions about webpack compilation statistics"
readme = "../../README.md"
license = "Apache-2.0"


[[bin]]
name = "webpack-q"
path = "./src/main.rs"

[dependencies]
webpack-q = { path = "../../crates/webpack-q", version = "0.2.0" }
clap = { version = "3", features = ['derive'] }
tracing = "0.1"
serde_json = "1"
serde = "1"
tracing-subscriber = "0.3"
anyhow = "1.0.58"
dot = "0.1.4"


